# This is a basic workflow to help you get started with Actions

name: Mermaid Export

# Controls when the workflow will run
on:
  push:
#     paths:
#       - 'flowchart.md'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  export_to_svg:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      

      # Runs a single command using the runners shell
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
        
      - name: Install Dependencies
        run: |
          npm install @mermaid-js/mermaid-cli 
          
      
      - name: Export to SVG
        run: ./node_modules/.bin/mmdc -i docs/flowchart.md -o output.svg
        
      - name: Save SVG to documentation folder
        run: |
          git add "docs/"
          git commit -m "Exported flowchart changes to svg.
          git push

